### ISSUE TITLE
startup script regenerates everything after docker-compose down -> docker-compose up

### ISSUE THREAD

**Issue by AleksMeshkov** [jjethwa/icinga2#116]
Here's my ```docker-compose.yaml```

```
services:
  icinga:
    environment:
      ICINGA_PASSWORD: ***
      ICINGAWEB2_PASSWORD: ***
      DIRECTOR_PASSWORD: ***
      IDO_PASSWORD: ***
      DEBIAN_SYS_MAINT_PASSWORD: ***
      ICINGAWEB2_ADMIN_USER: admin
      ICINGAWEB2_ADMIN_PASS: ***
      ICINGA2_USER_FULLNAME: ***
      APACHE2_HTTP: BOTH
      ICINGA2_FEATURE_DIRECTOR: 1
      DIRECTOR_KICKSTART: 0
    image: jordan/icinga2:2.7.0
    restart: always
    ports:
    - "5665:5665"
    - "3000:80"
    volumes:
    - ./etc/icinga2:/etc/icinga2 #rw  Icinga2 configuration folder
    - ./etc/icingaweb2:/etc/icingaweb2 #rw  Icingaweb2 configuration folder
    - ./var/lib/mysql:/var/lib/mysql #rw  MySQL Database
    - ./var/lib/icinga2:/var/lib/icinga2 #rw  Icinga2 Data
    - ./var/lib/php5/sessions:/var/lib/php5/sessions/ #rw  Icingaweb2 PHP Session Files

version: '3'
```

Then I perform ```docker-compose up -d``` and your startup script creates DB and initial config.
I make changes (create zone, templates, hosts etc).
Then I do ```docker-compose down``` and then ```docker-compose up -d``` again and you script reinits for ex. etc/icinga2/zones.conf file (with all my settings), recreates endpoint (with different name) and zone.

I don't want this behaviour. I want complete persistence between "docker-compose" down and "docker-compoese" up states.

Can you please tell me what am I missing? Thanks!
