### ISSUE TITLE
etc regenerating on every compose down and up

### ISSUE THREAD

**Issue by ScreamingDev** [jjethwa/icinga2#143]
Using this config:

```
version: "3"
services:
  test:
    image: jordan/icinga2
    hostname: icinga-test
    environment:
      APACHE2_HTTP: "BOTH"
    volumes:
      - "${VAR_DIR}/etc/icinga2:/etc/icinga2"
      - "${VAR_DIR}/mysql:/var/lib/mysql"
      - "${VAR_DIR}/var/lib/icinga2:/var/lib/icinga2"
```

And constantly restartting:

```
dcompose down && dcompose up -d && dcompose exec cng "egrep 'NodeName|TicketSalt' /etc/icinga2/constants.conf"
```

The token always changes,
the etc always rewritten.
How can this possibly work?
etc and other files should not change with every restart to have a stable config and tokens.
