### ISSUE TITLE
Problem using external mariadb in stack mode

### ISSUE THREAD

**Issue by Foxi352** [jjethwa/icinga2#149]
Hi. Great project, love it. Thanks for this.
Now i switched my docker to swarm mode and wanted to create a monitoring stack with multiple services. On my old setup i started all containers manually with `docker run`. Now i use a compose v3 file for my stack.

Since migrating to the compose / stack mode i can't get it to connect to my external mariadb service.
I correctly set the environment variables, and all services of the stack are in the same network. If i execute a shell in my icinga2 container i can `ping mariadb` and i can see the `MYSQL_ROOT_PASSWORD=<xxxxxx>` and `DEFAULT_MYSQL_HOST=mariadb` environment variables. But icinga always starts and installs it's own mysql daemon.

Is this a bug or am i on a wrong track ?

```
version: '3.2'
services:

    icinga2:
        hostname: icinga
        image: jordan/icinga2:2.8.0
        
        depends_on:
            - influxdb
            - mariadb
        
        ports:
            - '8083:80'
            - '5665:5665'

        volumes:
            - icinga2:/etc/icinga2
            - icinga2-sessions:/var/lib/php/sessions
            - icinga2-data:/var/lib/icinga2
            - icinga2-web:/etc/icingaweb2
            - icinga2-ssmtp:/etc/ssmtp
            - /etc/localtime:/etc/localtime:ro
        
        environment:
            - DEFAULT_MYSQL_HOST=mariadb
            - MYSQL_ROOT_PASSWORD=<xxxxxx>
            
        deploy:
            mode: global
            restart_policy:
                condition: always
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1gb

    grafana:
        [not relevant here]

    influxdb:
        [not relevant here]
    
    mariadb:
        hostname: mariadb
        image: mariadb:10
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        
        volumes:
            - mariadb:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro

        environment:
            - MYSQL_ROOT_PASSWORD=<xxxxx>

        deploy:
            restart_policy:
                condition: always
            mode: global
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1gb

```
