### ISSUE TITLE
Problem with docker compose environment

### ISSUE THREAD

**Issue by trickert76** [jjethwa/icinga2#246]
Hi, first thanks for this image!

Since some days I have a problem with it inside a docker-compose environment. The environment is:

```
# Ansible managed
version: '2.1'

services:
  icinga2:
    image: jordan/icinga2
    restart: always
    hostname: icinga2
    env_file:
      - .env
    volumes:
      - ./conf/icinga/etc/icinga2:/etc/icinga2
      - ./conf/icinga/etc/icingaweb2:/etc/icingaweb2
    ports:
      - "80:80"
      - "5667:5665"
    depends_on:
      - mysql
      - graphite

  graphite:
    image: graphiteapp/graphite-statsd:latest
    restart: always
    hostname: graphite

  mysql:
    image: mariadb:10.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.19.0.0/24
        - subnet: fc00:1900::/96
```

(I removed all irrelevant parts). The environment file contains:

```
MYSQL_ROOT_PASSWORD=rootpwd

ICINGA2_FEATURE_GRAPHITE=1
ICINGA2_FEATURE_GRAPHITE_HOST=graphite
ICINGA2_FEATURE_GRAPHITE_PORT=2003
ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
ICINGA2_FEATURE_GRAPHITE_SEND_METADATA=true
ICINGA2_FEATURE_DIRECTOR=false

DIRECTOR_KICKSTART=false

ICINGAWEB2_ADMIN_USER=admin
ICINGAWEB2_ADMIN_PASS=password
ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance

DEFAULT_MYSQL_HOST=mysql

MYSQL_INITDB_SKIP_TZINFO=1
```
After the first start (I removed `data/mysql`) I'm getting a running service - but, when I restart the service, I'm getting a:

    ...
    icinga2_1   | warning/cli: Feature 'command' already enabled.
    icinga2_1   | ERROR 1045 (28000): Access denied for user 'icinga2'@'fc00:1900::4' (using password: YES)
    icinga2_1   | run-parts: /opt/setup/50-icinga2 exited with return code 1

This is strange, because the password for the icinga2 mysql user, which is stored in `conf/icinga/etc/icingaweb2/resources.ini` and in `conf/icinga/etc/icinga2/features-enabled/ido-mysql.conf` can be used to log into the mysql container.:

    $> docker-compose exec mysql mysql -u icinga2 -p<pwd-from-file> icinga2idomysql -e 'show tables'
    $> docker-compose exec mysql mysql -u icinga2 -p<pwd-from-file> icingaweb2 -e 'show tables'

Also, when I look into mysql.user, I can see it, and the user is configured as icinga2@%

When I remove the database again, the service runs - so, it works only, when the initialize script generates a new secret during that run.

It seems to me, that the second run doesn't know about the "old" password.
