### ISSUE TITLE
 critical/cli: Cannot parse available features. Path '/etc/icinga2/features-available' does not exist.

### ISSUE THREAD

**Issue by AqujZ1K9** [jjethwa/icinga2#250]
Hi Guys,
am I the only one with this issue when creating the container from the provided docker-compose

`Pinging mysql:3306
critical/cli: Cannot parse available features. Path '/etc/icinga2/features-available' does not exist.
run-parts: /opt/setup/50-icinga2 exited with return code 1`

haven't changed anything at the compose-file.
Running docker on PhotonOs(x64).
Anything I'm not seeing here?
Thanks!

**Comment by jjethwa** [comment]
Hi @AqujZ1K9 

Hmm, that's strange.  What version of docker are you using?  The error refers to this script: https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/50-icinga2

/etc/icinga2/features-available should exist as it's part of the standard icinga2 install, but we might need to add a line to create it if it doesn't exist.

**Comment by AqujZ1K9** [comment]
@jjethwa  thanks for reaching out!
Docker version 19.03.10, build 9424aea

whats stange that the binding seems to be ok. Anything I could check ?

**Comment by jjethwa** [comment]
No problem 😃   Can you double check the /etc/icinga2 volume and see if it has the features-available directory under it?  Sorry, this will require digging under your docker var directory.

**Comment by AqujZ1K9** [comment]
`root@icinga2:/etc/icinga2/features-available# ls
api.conf      command.conf    debuglog.conf       gelf.conf      icingadb.conf   influxdb.conf    mainlog.conf       opentsdb.conf  statusdata.conf
checker.conf  compatlog.conf  elasticsearch.conf  graphite.conf  ido-mysql.conf  livestatus.conf  notification.conf  perfdata.conf  syslog.conf
root@icinga2:/etc/icinga2/features-available# `

within the container it seems to be all up and running.
![etc](https://user-images.githubusercontent.com/76105246/102393232-5ebf1900-3fd8-11eb-81cd-23eb0696cdeb.JPG)

**Comment by jjethwa** [comment]
Could it be that it's somehow trying to run the script on the mysql container?  I've never seen that happen before though.

**Comment by AqujZ1K9** [comment]
the problem seems to be the line : `icinga2 feature enable ido-mysql livestatus compatlog command`

the whole icinga2 cli seems to be broken for me.

e.g.: `icinga2 feature list`

`root@icinga2:/var/log/icinga2/crash# icinga2 feature list
Could not create directory '/var/log/icinga2/crash': Error 13, Permission denied
critical/Application: Error: Function call 'glob' for file '/etc/icinga2/features-available/*.conf' failed with error code 13, 'Permission denied'`

any Idea where to go for that ?

**Comment by jjethwa** [comment]
Thanks for the additional details, this looks like it's actually erroring out in the CLI API calls, I originally thought it was the docker scripts.  Can you check on the existence of /var/log/icinga2 and the permissions and ownership?  Can you also check the permissions and ownership for /etc/icinga2 and etc/icinga2/features-available/*.conf as well?

**Comment by AqujZ1K9** [comment]
/var/log/icinga2 exists:
`drwxr-xr-x 3 nagios      adm    4096 Dec 16 22:41 icinga2`

/etc/icinga2
`drwxr-xr-x 8 nagios root    4096 Dec 16 22:41 icinga2`

/etc/icinga2/features-available/
`drwxr-x--- 2 nagios root 4096 Dec 16 22:41 .`

/etc/icinga2/features-available/*.conf
`-rw-r--r-- 1 nagios root  183 Dec 16 22:41 api.conf
-rw-r--r-- 1 nagios root  112 Dec 16 22:41 checker.conf
-rw-r--r-- 1 nagios root  140 Dec 16 22:41 command.conf
-rw-r--r-- 1 nagios root  159 Dec 16 22:41 compatlog.conf
-rw-r--r-- 1 nagios root  235 Dec 16 22:41 debuglog.conf
-rw-r--r-- 1 nagios root  193 Dec 16 22:41 elasticsearch.conf
-rw-r--r-- 1 nagios root  206 Dec 16 22:41 gelf.conf
-rw-r--r-- 1 nagios root  190 Dec 16 22:41 graphite.conf
-rw-r--r-- 1 nagios root   91 Dec 16 22:41 icingadb.conf
-rw------- 1 nagios root  241 Dec 16 22:41 ido-mysql.conf
-rw-r--r-- 1 nagios root  560 Dec 16 22:41 influxdb.conf
-rw-r--r-- 1 nagios root  127 Dec 16 22:41 livestatus.conf
-rw-r--r-- 1 nagios root  159 Dec 16 22:41 mainlog.conf
-rw-r--r-- 1 nagios root  129 Dec 16 22:41 notification.conf
-rw-r--r-- 1 nagios root  564 Dec 16 22:41 opentsdb.conf
-rw-r--r-- 1 nagios root  146 Dec 16 22:41 perfdata.conf
-rw-r--r-- 1 nagios root  225 Dec 16 22:41 statusdata.conf
-rw-r--r-- 1 nagios root  127 Dec 16 22:41 syslog.conf`

additon, when logging into the container as "nagios" I get:

`bash: /etc/bash.bashrc: Permission denied
bash: /var/lib/nagios/.bashrc: Permission denied`

**Comment by jjethwa** [comment]
Thanks, those permissions look correct and you won't be able to start an interactive shell with the nagios user as it's meant for daemon use only. Is there anything in the API log under /var/log/icinga2 that might be related?  Sorry about all of the back and forth, I've just never seen this before, so I'm trying to collect as much information on it.

**Comment by AqujZ1K9** [comment]
no logs under /var/log/icinga2
Icinga2 CLi can't even write Logs:
`icinga2 feature list`
`Could not create directory '/var/log/icinga2/crash': Error 13, Permission denied`

Thanks for helping so far!

**Comment by jjethwa** [comment]
I'll try pulling down Photon later today and see if I can reproduce the issue. In the meantime, try:

```
mkdir -p /var/log/icinga2/crash
chown -R nagios:adm /var/log/icinga2
```
And running the CLI command again.  Let's see if we can get something in the logs this time 😞

**Comment by AqujZ1K9** [comment]
doesn't seem to do anything /help...

**Comment by jjethwa** [comment]
So you're getting the error still when running the CLI command?

**Comment by AqujZ1K9** [comment]
yes sir

**Comment by jjethwa** [comment]
Eek, thanks for your patience @AqujZ1K9   I'll get that VM going a bit later and test it out.

**Comment by jjethwa** [comment]
Hi @AqujZ1K9 

Need just a little more time, I ran an update on my laptop last night that is causing issues

**Comment by AqujZ1K9** [comment]
no worries. I've changed to an Debian Buster Host now and don't have these Issues anymore. But his can still be interesting for other tho.
Thanks for helping out!

**Comment by jjethwa** [comment]
Thanks for the update, @AqujZ1K9 

Once I get my laptop updated properly, I'll try to spend time and see if I can figure it out.

**Comment by gianmarco-mameli** [comment]
Hi, sorry for attaching my problem to this old issue, but in fact I've the same problem, same error as @AqujZ1K9.
I've builded my image to updating Icinga2 at version 2.13.1. When starting the error is

_critical/cli: Cannot parse available features. Path '/etc/icinga2/features-available' does not exist._

the folder is mapped to a volume on a glusterfs, operating system Debian Bullseye 11.0 arm64
Already checked/performed all solutions of this thread

Thans

**Comment by jjethwa** [comment]
Hi @gianmarco-mameli 

No problem!  I had forgotten about this issue, sorry @AqujZ1K9 😞 

Is etc/icinga2/features-available available in the volume?  What are the permissions?  The CLI utility will make modifications such as symlinking to files inside.

**Comment by gianmarco-mameli** [comment]
the folder is available, and the permissions are correct. Deploying an old image builded by me it works without problems.
I'm expert of Icinga2 because I'm administrator at my work of an infrastructure with 2 master and 22 satellites. I've tried any solution I know but it doesn't work. The folder is in the correct place and with correct permission but strangely the command for enable features fail.
I need the docker image for my raspberry pis cluster.
Maybe the problem is the glusterfs, but the other user uses normal fs

**Comment by gianmarco-mameli** [comment]
update: removing volume /etc/icinga2 works, but i've noticed the version of icinga is very old.
I'm trying rebuild the image with raspbian repo for armhf packages

**Comment by jjethwa** [comment]
Hi @gianmarco-mameli 

I would not think it's gluster as that would be transparent to the app.  Is there anything else interesting in the logs that might help?  I'm wondering if you can start the container in interactive mode so you can poke around inside?  You might have to override the run script

**Comment by jjethwa** [comment]
Just saw the new comment, so some progress.  Keep me in the loop, I haven't used the rasbian repo 😃

**Comment by gianmarco-mameli** [comment]
Hi, after 1 year, I decided to rebuild this image for my Raspberry Pi Docker Swarm cluster, but errors still present, with or without mounted volumes.
For testing I forked your project and made some adjustments to docker file, like adding packages and changing base image
I've tried with debian:bookworm-slim and ubuntu:kinetic, these are devel images but the only version that have all icinga2 packages updated form armhf platform

examples:
critical/cli: Cannot parse available features. Path '/etc/icinga2/features-available' does not exist.
Could not create directory '/var/log/icinga2/crash': Error 13, Permission denied
critical/Application: Error: Function call 'glob' for file '/etc/icinga2/features-available/*.conf' failed with error code 13, 'Permission denied'

**Comment by jjethwa** [comment]
Hi @gianmarco-mameli 

Sorry, I still don't have a Pi setup to test myself, so I'll need to rely on your testing and reports.  Are these errors occuring at container startup or during the image building process?

Can you provide the docker run command you are using?

**Comment by gianmarco-mameli** [comment]
Hi @jjethwa no problem, I try to explain as must as possible to you.
The errors came out when I try to run the entrypoint "/opt/run" or in a simple check running "icinga2 daemon -C" or "icinga2 feature list".
I cannot explain why, but it seems that icinga is not capable to read any of the folder like cache or config, or log. I already tried modifying the permission in every method i know and found on web.
The deploy is made by a compose file in a stack that you can find below, ( I removed some non important info and replaced with [ ] )
If you think the volumes in GlusterFS filesystem maybe are the problem (me too I supposed the same), I can replicate without any mounted volumes.
The platform is Armv7, docker running on Raspbian Bullseye on 3x Rapsberry pi 4 4gb

Let me know if you need more information

```
version: "3.8"
services:
  icinga2:
    image: <localregistry>:5000/icinga2:latest
    hostname: icinga2.docker.local
    volumes:
      - icinga2_etc_icinga2:/etc/icinga2
      - icinga2_etc_icingaweb2:/etc/icingaweb2
      - icinga2_var_lib_icinga2:/var/lib/icinga2
      - icinga2_var_lib_php_sessions:/var/lib/php/sessions
      - icinga2_var_log_apache2:/var/log/apache2
      - icinga2_var_log_icinga2:/var/log/icinga2
      - icinga2_var_log_icingaweb2:/var/log/icingaweb2
      - icinga2_var_log_supervisor:/var/log/supervisor
      - icinga2_usr_lib_nagios_extra_plugins:/usr/lib/nagios/extra_plugins
      - icinga2_var_lib_centreon_centplugins:/var/lib/centreon/centplugins
      - icinga2_var_cache_icinga2:/var/cache/icinga2
      - "/etc/msmtprc:/etc/msmtprc:ro"
      - "/etc/aliases:/etc/aliases:ro"
      - "/etc/locale.gen:/etc/locale.gen:ro"
    ports:
      - "5665:5665"
    environment:
      - TZ=Europe/Rome
      - ICINGA2_FEATURE_GRAPHITE=true
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      - ICINGA2_FEATURE_GRAPHITE_SEND_THRESHOLDS=true
      - ICINGA2_FEATURE_GRAPHITE_SEND_METADATA=false
      - ICINGAWEB2_ADMIN_USER=admin
      - ICINGAWEB2_ADMIN_PASS=***
      - ICINGAWEB2_FEATURE_DIRECTOR=true
      # - ICINGA2_FEATURE_DIRECTOR_KICKSTART=false
      - ICINGA2_FEATURE_DIRECTOR_USER=icinga2-director
      - ICINGA2_FEATURE_DIRECTOR_PASS=***
      # - ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
      - DEFAULT_MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=***
      - DEFAULT_MYSQL_PASS=***
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        [ ]
    networks:
      - traefik_network

volumes:
  icinga2_etc_icinga2:
    driver: glusterfs
    name: gfs/icinga2/etc/icinga2
  icinga2_etc_icingaweb2:
    driver: glusterfs
    name: gfs/icinga2/etc/icingaweb2
  icinga2_var_lib_icinga2:
    driver: glusterfs
    name: gfs/icinga2/var/lib/icinga2
  icinga2_var_lib_php_sessions:
    driver: glusterfs
    name: gfs/icinga2/var/lib/php/sessions
  icinga2_var_log_apache2:
    driver: glusterfs
    name: gfs/icinga2/var/log/apache2
  icinga2_var_log_icinga2:
    driver: glusterfs
    name: gfs/icinga2/var/log/icinga2
  icinga2_var_log_icingaweb2:
    driver: glusterfs
    name: gfs/icinga2/var/log/icingaweb2
  icinga2_var_log_supervisor:
    driver: glusterfs
    name: gfs/icinga2/var/log/supervisor
  icinga2_usr_lib_nagios_extra_plugins:
    driver: glusterfs
    name: gfs/icinga2/usr/lib/nagios/extra_plugins
  icinga2_var_lib_centreon_centplugins:
    driver: glusterfs
    name: gfs/icinga2/var/lib/centreon/centplugins
  icinga2_var_cache_icinga2:
    driver: glusterfs
    name: gfs/icinga2/var/cache/icinga2

networks:
  traefik_network:
    external: true
    name: traefik_network
```
