### ISSUE TITLE
Fancy Dashboard

### ISSUE THREAD

**Issue by gvenka008c** [jjethwa/icinga2#37]
@jjethwa Got any plans to add fancy dashboards to the icinga2 docker version?
https://github.com/Icinga/icinga-vagrant/blob/master/README.md#icinga2x

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Icinga2 includes a module to export data to Graphite's carbon daemon already.  If you have a Graphite instance set up already, you just need to start the container with these environment variables

```
ICINGA2_FEATURE_GRAPHITE - false (default).  Set to true or 1 to enable graphite writer
ICINGA2_FEATURE_GRAPHITE_HOST - graphite (default).  Set to link name, hostname, or IP address where Carbon daemon is running
ICINGA2_FEATURE_GRAPHITE_PORT - 2003 (default).  Carbon port
```

Once you have Graphite setup and Icinga2 sending data to the carbon daemon, you would use Grafana to create the nice looking dashboards :)

**Comment by Quentinvarquet** [comment]
I confirm, it works ! :-) 

I am using this image if it can help you : https://hub.docker.com/r/choopooly/grafana-graphite/

**Comment by gvenka008c** [comment]
@jjethwa Thanks.

@Quentinvarquet Does this runs as an individual container and talks to icinga to get the data and display it in Dashboard?

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Yes, the carbon daemon will run in a separate container.  The container that @Quentinvarquet linked you to has everything you need to get graphite and grafana going 🙂. You would link the icinga2 container to the graphite one.

**Comment by gvenka008c** [comment]
@Quentinvarquet I pull the image and ran as below. But I am not able to access the dashboard.

http://ipadddress:3081

```
docker run -d -p 3081:80 -p 2003:2003 -p 8125:8125/udp -p 8126:8126 --name grafana-dashboard choopooly/grafana-graphite

```

**Comment by gvenka008c** [comment]
@Quentinvarquet ran the container with below setting but can't get to the graphana dashboard. Any thoughts?

```
docker run -d -e HOST_HOSTNAME=`hostname -i` -p 3081:80 -p 2003:2003 -p 8125:8125/udp -p 8126:8126 --name grafana-dashboard choopooly/grafana-graphite

```

**Comment by jjethwa** [comment]
Hi @gvenka008c 

According to the readme ( https://github.com/choopooly/docker-grafana-graphite/blob/master/README.md ), grafana is running on port 80 :)

**Comment by gvenka008c** [comment]
@jjethwa I mapped it to 3081 when running the container
-p 3081:80

**Comment by jjethwa** [comment]
Ah whoops I missed your mapping, @gvenka008c 

As a test, I tried running:
```
sudo docker run -d -e HOST_HOSTNAME=`hostname -i` -p 3081:80 --name grafana-dashboard choopooly/grafana-graphite
```
And was able to connect to the grafana instance at:

```
http://<HOSTNAME>:3081/#/dashboard/file/default.json
```

**Comment by gvenka008c** [comment]
@jjethwa Thanks. I am not able to connect to it. I have opened all the ports as well on the host. Not sure what i am missing here.

```
http://xx.xxx.xxx.xxx:3081/#/dashboard/file/default.json

```

I was able to connect to icinga2 running on the same host

```
http://xx.xxx.xxx.xxx:3080/icingaweb2/dashboard

```

**Comment by jjethwa** [comment]
@gvenka008c 

Hmm, unfortunately I don't know what's going on as I don't use that container myself.

I use:

https://hub.docker.com/r/sitespeedio/graphite/  for graphite
and
https://hub.docker.com/r/grafana/grafana/ for grafana

**Comment by gvenka008c** [comment]
@jjethwa Thanks. Will try your docker images. Any reason why you use both graphite and graphana?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

I don't maintain those images, but we use them for our production data without issue 🙂

Graphite has the carbon daemon, aggregator, and graphite front-end, but Grafana has a great interface.  You use graphite as the data source.  You're going to love it!

**Comment by gvenka008c** [comment]
@jjethwa So you mean to say you have 3 docker containers running? One for icinga, one for graphite and antother for graphana? Send data from icinga to graphite and then pull the dashboard using graphite?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Yes, that's the preferred way when working with containers.  Each specific service is in it's own container so they do not affect each other if changes are made to shared libraries, etc.

So one example setup would be 1 grafana (linked to graphite), 1 graphite, and 1 icinga2 (linked to graphite)

Here is an example (Make sure to use volumes for all of the containers to store the database, configs, etc so they persist across container restarts)

You need to start the graphite container first, see the quick start section: https://github.com/sitespeedio/docker-graphite-statsd/blob/master/README.md 

Next, start Icinga (sorry I had a mistake in my readme for the Graphite example.  I've updated it)

```
sudo docker run --link graphite:graphite -e ICINGA2_FEATURE_GRAPHITE=true -e ICINGA2_FEATURE_GRAPHITE_HOST=graphite -e ICINGA2_FEATURE_GRAPHITE_PORT=2003 -t jordan/icinga2:latest
```

Start grafana: https://github.com/grafana/grafana-docker/blob/master/README.md

Depending on how you set up the graphite instance, you might need to link the grafana instance to it as well so the datasource will work.

Remember to use volumes for all of the containers so your data persists and keep in mind that if a container that was linked to is restarted, you will need to restart the container that is linking to it to get the networking set up again properly :)

**Comment by Quentinvarquet** [comment]
Hello everyone,

@jjethwa  I tried your graphite and grafana container because the version of grafana I am usijng is old and graphite is in the same container. (I linked Icinga et Grafana to the graphite container)

Everything is working, I can see my data from icinga in my graphite container.

But I don't know if @gvenka008c wil have the same problem. When I add a new data source in my grafana container I have this message : 

`Cannot read property 'message' of null`

You can see in screenshot the configuration : 

![image](https://cloud.githubusercontent.com/assets/7962157/16524270/da24d872-3fa7-11e6-9294-41cf74264cd0.png)


Maybe it can help, I will share you my docker-compose file (without the volumes)

```
icinga:
  image: jordan/icinga2 
  environment:
   - ICINGA_PASSWORD=your_password
   - ICINGA_WEB_PASSWORD=your_password
   - ICINGAWEB2_PASSWORD=your_password
   - IDO_PASSWORD=your_password
   - DIRECTOR_PASSWORD=your_password
   - DEBIAN_SYS_MAINT_PASSWORD=your_password
   - ICINGA2_FEATURE_GRAPHITE=true
   - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
   - ICINGA2_FEATURE_GRAPHITE_PORT=2003
  links:
   - graphite:graphite
  restart: always 
  ports:
   - "8081:80"
  

graphite:
  image: sitespeedio/graphite
  ports:
   - "2003:2003"
   - "8080:80"
  restart: always 
  volumes:
   - ./graphite/storage:/opt/graphite/storage/whisper

grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  restart: always 
  links:
   - graphite:graphite
```
