### ISSUE TITLE
Icinga : docker restart=always not working

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#43]
Hello, I tried to see if the restart=always was working (I am using docker-compose)

The restart=always is working for all my container in production server (20 containers). I just did 

`service docker restart
`

20 containers restarted directly after the restart of the service but not the icinga one.

When I try to start it, I have this message :   

> ERROR: rpc error: code = 6 desc = "mkdir /run/containerd/9de1f2232f43f567c57574e46dee183cba4081bb078694112c1cbb668061405e: file exists"

Here is an example of one docker-compose.yml file, if you try it, you ll have the same problem

```
icinga:
  image: jordan/icinga2
  environment:
   - ICINGA_PASSWORD=password
   - ICINGA_WEB_PASSWORD=password
   - ICINGAWEB2_PASSWORD=password
   - IDO_PASSWORD=password
   - DIRECTOR_PASSWORD=password
   - DEBIAN_SYS_MAINT_PASSWORD=password
   - DIRECTOR_KICKSTART=false
  ports:
   - "80:80" 
  restart: always
```

Do you know why ?
