### ISSUE TITLE
Icingaweb2 : Permission denied on restart

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#49]
Hello,

I just installed the last version of Icinga on a new server.

I have some volumes (for example ./icingaweb2:/etc/icingaweb2).

But I have a problem. Everytime I restart my Icinga container, I have this :

![image](https://cloud.githubusercontent.com/assets/7962157/18632668/edf052c2-7e78-11e6-8ef4-975f976aa067.png)

I need to connect in my container and fix the permissions by myself in the folder /etc/icingaweb2. I never had this problem before.
 
Do you know why ?

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Hmm, what commands are you running to fix the permissions?  It might be due to a recent PR: https://github.com/jjethwa/icinga2/pull/44

**Comment by Quentinvarquet** [comment]
Hello,

I am on a DEV server, so for now I am just using a 

`
chmod -R 755 icingaweb2
`

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Are you using a volume for /etc/icingaweb2 ?

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Try the latest build and see if that works for you.  Looks like one of the recent pull requests might have introduced that bug :)

**Comment by Quentinvarquet** [comment]
Hello @jjethwa 

I tried your fix but I still have it and ... it's my fault ! :-) 

I was still using the volume "workflow" from the very old version of docker-compose

Before, we had to do

`docker cp icinga_container:/etc/icingaweb2 icingaweb2`

Then create the volume from this **docker cp** and fix the permissions...

Today I saw, with the last version of docker-compose, you just have to add your volume in your docker-compose.yml, for example :


```
icinga:
  image: jordan/icinga2
  volumes:
   - ./volumes/icingaweb2:/etc/icingaweb2
  environment:
   - ICINGA_PASSWORD=icinga
   - ICINGA_WEB_PASSWORD=icinga
   - ICINGAWEB2_PASSWORD=icinga
   - IDO_PASSWORD=icinga
   - DIRECTOR_PASSWORD=icinga
   - DEBIAN_SYS_MAINT_PASSWORD=icinga
   - DIRECTOR_KICKSTART=false
  ports:
   - 81:80 
```

And docker-compose will automatically mount your volumes with the right permissions, easier than before !

So everything is fine, the problem was .. from me because I updated docker-compose without reading all the new features from my very old version ... :-) 


Thank you for your time, everything is working well !
